name: find good stock

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install pandas
        pip install lxml
        pip install tushare
        pip install tqdm
    - name: get real time stock info and 4 ma index 
      run: |
        python ./python_scripts/find_good_stock.py ${{secrets.tushare_token}}
    - name: sync github
      run: |
        git config --global user.email ${{secrets.mygithub}}
        git config --global user.name ${{secrets.mygithub_name}}
        git pull
        git add *
        git commit -m 'sync github'
        git push
