name: Gitalk

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write
  issues: write

jobs:
  gitalk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Run Gitalk Action
        uses: Yikun/gitalk-actions@v0.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: zluckyhou.github.com  # 请确认这是正确的仓库名
          owner: zluckyhou
          clientId: ${{ secrets.GITALK_CLIENT_ID }}
          clientSecret: ${{ secrets.GITALK_CLIENT_SECRET }}
